[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv venv",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". venv/bin/activate && python app.py"